/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/py/ROSTryphon_Organized/src/sensors/msg/compass.msg
 *
 */


#ifndef SENSORS_MESSAGE_COMPASS_H
#define SENSORS_MESSAGE_COMPASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensors
{
template <class ContainerAllocator>
struct compass_
{
  typedef compass_<ContainerAllocator> Type;

  compass_()
    : id(0)
    , rz()
    , head_init(0)  {
      rz.assign(0);
  }
  compass_(const ContainerAllocator& _alloc)
    : id(0)
    , rz()
    , head_init(0)  {
      rz.assign(0);
  }



   typedef int32_t _id_type;
  _id_type id;

   typedef boost::array<int32_t, 10>  _rz_type;
  _rz_type rz;

   typedef int32_t _head_init_type;
  _head_init_type head_init;




  typedef boost::shared_ptr< ::sensors::compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::compass_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct compass_

typedef ::sensors::compass_<std::allocator<void> > compass;

typedef boost::shared_ptr< ::sensors::compass > compassPtr;
typedef boost::shared_ptr< ::sensors::compass const> compassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::compass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::compass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'sensors': ['/home/py/ROSTryphon_Organized/src/sensors/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensors::compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::compass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::compass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::compass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::compass_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9d9eecbee8c0fcf7f1f2c957b3f53e";
  }

  static const char* value(const ::sensors::compass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9d9eecbee8c0fcULL;
  static const uint64_t static_value2 = 0xf7f1f2c957b3f53eULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/compass";
  }

  static const char* value(const ::sensors::compass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32[10] rz\n\
int32 head_init\n\
";
  }

  static const char* value(const ::sensors::compass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::compass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.rz);
      stream.next(m.head_init);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct compass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::compass_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "rz[]" << std::endl;
    for (size_t i = 0; i < v.rz.size(); ++i)
    {
      s << indent << "  rz[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.rz[i]);
    }
    s << indent << "head_init: ";
    Printer<int32_t>::stream(s, indent + "  ", v.head_init);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_COMPASS_H
