/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/py/ROSTryphon_Organized/src/sensors/msg/imuros.msg
 *
 */


#ifndef SENSORS_MESSAGE_IMUROS_H
#define SENSORS_MESSAGE_IMUROS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensors
{
template <class ContainerAllocator>
struct imuros_
{
  typedef imuros_<ContainerAllocator> Type;

  imuros_()
    : accel()
    , gyro()
    , magn()  {
      accel.assign(0.0);

      gyro.assign(0.0);

      magn.assign(0.0);
  }
  imuros_(const ContainerAllocator& _alloc)
    : accel()
    , gyro()
    , magn()  {
      accel.assign(0.0);

      gyro.assign(0.0);

      magn.assign(0.0);
  }



   typedef boost::array<double, 3>  _accel_type;
  _accel_type accel;

   typedef boost::array<double, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<double, 3>  _magn_type;
  _magn_type magn;




  typedef boost::shared_ptr< ::sensors::imuros_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::imuros_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct imuros_

typedef ::sensors::imuros_<std::allocator<void> > imuros;

typedef boost::shared_ptr< ::sensors::imuros > imurosPtr;
typedef boost::shared_ptr< ::sensors::imuros const> imurosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::imuros_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::imuros_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'sensors': ['/home/py/ROSTryphon_Organized/src/sensors/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensors::imuros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::imuros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::imuros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::imuros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::imuros_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::imuros_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::imuros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b01df9aeabf2ec2a45aad9d35856770e";
  }

  static const char* value(const ::sensors::imuros_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb01df9aeabf2ec2aULL;
  static const uint64_t static_value2 = 0x45aad9d35856770eULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::imuros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/imuros";
  }

  static const char* value(const ::sensors::imuros_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::imuros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] accel\n\
float64[3] gyro\n\
float64[3] magn\n\
";
  }

  static const char* value(const ::sensors::imuros_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::imuros_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accel);
      stream.next(m.gyro);
      stream.next(m.magn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct imuros_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::imuros_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::imuros_<ContainerAllocator>& v)
  {
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.accel[i]);
    }
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "magn[]" << std::endl;
    for (size_t i = 0; i < v.magn.size(); ++i)
    {
      s << indent << "  magn[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.magn[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_IMUROS_H
