/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/py/ROSTryphon_Organized/src/sensors/msg/sonarArray.msg
 *
 */


#ifndef SENSORS_MESSAGE_SONARARRAY_H
#define SENSORS_MESSAGE_SONARARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensors/sonar.h>

namespace sensors
{
template <class ContainerAllocator>
struct sonarArray_
{
  typedef sonarArray_<ContainerAllocator> Type;

  sonarArray_()
    : sonars()  {
    }
  sonarArray_(const ContainerAllocator& _alloc)
    : sonars(_alloc)  {
    }



   typedef std::vector< ::sensors::sonar_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensors::sonar_<ContainerAllocator> >::other >  _sonars_type;
  _sonars_type sonars;




  typedef boost::shared_ptr< ::sensors::sonarArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::sonarArray_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct sonarArray_

typedef ::sensors::sonarArray_<std::allocator<void> > sonarArray;

typedef boost::shared_ptr< ::sensors::sonarArray > sonarArrayPtr;
typedef boost::shared_ptr< ::sensors::sonarArray const> sonarArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::sonarArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::sonarArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'sensors': ['/home/py/ROSTryphon_Organized/src/sensors/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensors::sonarArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::sonarArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::sonarArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::sonarArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::sonarArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::sonarArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::sonarArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afeb67b4dccb598c2a418c6a2f41b00b";
  }

  static const char* value(const ::sensors::sonarArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafeb67b4dccb598cULL;
  static const uint64_t static_value2 = 0x2a418c6a2f41b00bULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::sonarArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/sonarArray";
  }

  static const char* value(const ::sensors::sonarArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::sonarArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sonar[] sonars\n\
\n\
================================================================================\n\
MSG: sensors/sonar\n\
int32 id\n\
int32[10] distance\n\
";
  }

  static const char* value(const ::sensors::sonarArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::sonarArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sonars);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sonarArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::sonarArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::sonarArray_<ContainerAllocator>& v)
  {
    s << indent << "sonars[]" << std::endl;
    for (size_t i = 0; i < v.sonars.size(); ++i)
    {
      s << indent << "  sonars[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensors::sonar_<ContainerAllocator> >::stream(s, indent + "    ", v.sonars[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_SONARARRAY_H
