"""autogenerated by genpy from sensors/motor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motor(genpy.Message):
  _md5sum = "1b82f96a00d42a296623e233e7741a45"
  _type = "sensors/motor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id
int32 rpm
int32 temp
int32 volt
int32 curr
int32 dir
int32 speed

"""
  __slots__ = ['id','rpm','temp','volt','curr','dir','speed']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,rpm,temp,volt,curr,dir,speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.rpm is None:
        self.rpm = 0
      if self.temp is None:
        self.temp = 0
      if self.volt is None:
        self.volt = 0
      if self.curr is None:
        self.curr = 0
      if self.dir is None:
        self.dir = 0
      if self.speed is None:
        self.speed = 0
    else:
      self.id = 0
      self.rpm = 0
      self.temp = 0
      self.volt = 0
      self.curr = 0
      self.dir = 0
      self.speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.id, _x.rpm, _x.temp, _x.volt, _x.curr, _x.dir, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.id, _x.rpm, _x.temp, _x.volt, _x.curr, _x.dir, _x.speed,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_7i.pack(_x.id, _x.rpm, _x.temp, _x.volt, _x.curr, _x.dir, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.id, _x.rpm, _x.temp, _x.volt, _x.curr, _x.dir, _x.speed,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7i = struct.Struct("<7i")
