"""autogenerated by genpy from sensors/sonarArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensors.msg

class sonarArray(genpy.Message):
  _md5sum = "afeb67b4dccb598c2a418c6a2f41b00b"
  _type = "sensors/sonarArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sonar[] sonars

================================================================================
MSG: sensors/sonar
int32 id
int32[10] distance

"""
  __slots__ = ['sonars']
  _slot_types = ['sensors/sonar[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sonars

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sonarArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sonars is None:
        self.sonars = []
    else:
      self.sonars = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.sonars)
      buff.write(_struct_I.pack(length))
      for val1 in self.sonars:
        buff.write(_struct_i.pack(val1.id))
        buff.write(_struct_10i.pack(*val1.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.sonars is None:
        self.sonars = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sonars = []
      for i in range(0, length):
        val1 = sensors.msg.sonar()
        start = end
        end += 4
        (val1.id,) = _struct_i.unpack(str[start:end])
        start = end
        end += 40
        val1.distance = _struct_10i.unpack(str[start:end])
        self.sonars.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.sonars)
      buff.write(_struct_I.pack(length))
      for val1 in self.sonars:
        buff.write(_struct_i.pack(val1.id))
        buff.write(val1.distance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.sonars is None:
        self.sonars = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sonars = []
      for i in range(0, length):
        val1 = sensors.msg.sonar()
        start = end
        end += 4
        (val1.id,) = _struct_i.unpack(str[start:end])
        start = end
        end += 40
        val1.distance = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=10)
        self.sonars.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_10i = struct.Struct("<10i")
